import React from "react";
import { render } from "react-dom";
import Gallery from "react-photo-gallery";
//import Test1 from './images/1-by-1.png';

// https://stackoverflow.com/questions/44607396/importing-multiple-files-in-react
/*
function importAll(r) {
    let images = {};
    r.keys().map((item, index) => { images[item.replace('./', '')] = r(item); });
    return images;
}

const images = importAll(require.context('./images', false, '/\.(png|jpe?g|svg)$/'));
*/

const photos = [
    {
        src:"https://i.imgur.com/ZcOqzJs.png",
        width:589,
        height:1064
    },
    {
        src:"https://i.imgur.com/tzgtYRD.png",
        width:1358,
        height:885
    },
    {
        src:"https://i.imgur.com/GJI0Ob1.png",
        width:1300,
        height:885
    },
    {
        src:"https://i.imgur.com/yDS61Nq.png",
        width:766,
        height:708
    },
    {
        src:"https://i.imgur.com/gXcmfGn.png",
        width:1533,
        height:885
    },
    {
        src:"https://i.imgur.com/m97LE24.png",
        width:710,
        height:708
    },
    {
        src:"https://i.imgur.com/m1ISSUu.png",
        width:885,
        height:885
    },
    {
        src:"https://i.imgur.com/2sjKb0D.png",
        width:1241,
        height:708
    },
    {
        src:"https://i.imgur.com/tzHndL7.png",
        width:1181,
        height:1179
    },
    {
        src:"https://i.imgur.com/jrpZlLQ.png",
        width:1062,
        height:1062
    },
    {
        src:"https://i.imgur.com/G9KQMjK.png",
        width:1241,
        height:708
    },
    {
        src:"https://i.imgur.com/t00gBh8.png",
        width:1239,
        height:766
    },
    {
        src:"https://i.imgur.com/675zS27.png",
        width:1479,
        height:885
    },
    {
        src:"https://i.imgur.com/RBtiSCN.png",
        width:589,
        height:887
    },
    {
        src:"https://i.imgur.com/CMixdiK.png",
        width:1418,
        height:1064
    },
    {
        src:"https://i.imgur.com/zZ7lg9H.png",
        width:1062,
        height:1062
    },
    {
        src:"https://i.imgur.com/fnCNNVQ.png",
        width:1652,
        height:885
    },
    {
        src:"https://i.imgur.com/AAyT4fF.png",
        width:1772,
        height:1179
    },
    {
        src:"https://i.imgur.com/GV6SDUw.png",
        width:1183,
        height:1066
    },
    {
        src:"https://i.imgur.com/pCCRx9w.png",
        width:1210,
        height:1062
    },
    {
        src:"https://i.imgur.com/jvYZv3L.png",
        width:1239,
        height:1179
    },
    {
        src:"https://i.imgur.com/edwnV7Q.png",
        width:708,
        height:1062
    },
    {
        src:"https://i.imgur.com/rZ9mVeC.png",
        width:887,
        height:591
    },
    {
        src:"https://i.imgur.com/G65tNGk.png",
        width:1418,
        height:1179
    },
    {
        src:"https://i.imgur.com/3gmMXqz.png",
        width:824,
        height:1533
    },
    {
        src:"https://i.imgur.com/dWzQjx1.png",
        width:1768,
        height:1179
    },
    {
        src:"https://i.imgur.com/WuN2wA0.png",
        width:589,
        height:1062
    },
    {
        src:"https://i.imgur.com/7DOnxei.png",
        width:1418,
        height:1181
    },
    {
        src:"https://i.imgur.com/DSVy121.png",
        width:768,
        height:1179
    },
    {
        src:"https://i.imgur.com/5IrMpE1.png",
        width:827,
        height:1179
    },
    {
        src:"https://i.imgur.com/LDeFBmI.png",
        width:1481,
        height:1179
    },
    {
        src:"https://i.imgur.com/BlEKkNR.png",
        width:2060,
        height:885
    },
    {
        src:"https://i.imgur.com/TUqvjTV.png",
        width:1768,
        height:1179
    },
    {
        src:"https://i.imgur.com/oxTpZ54.png",
        width:1768,
        height:1179
    },
    {
        src:"https://i.imgur.com/kTrN5qZ.png",
        width:1122,
        height:1125
    },
    {
        src:"https://i.imgur.com/DO5aNOb.png",
        width:1179,
        height:1179
    },
    {
        src:"https://i.imgur.com/TODEKJp.png",
        width:1772,
        height:1179
    },
    {
        src:"https://i.imgur.com/C8jcGTi.png",
        width:708,
        height:1062
    },
    {
        src:"https://i.imgur.com/3d0JFDS.png",
        width:1127,
        height:1125
    },
    {
        src:"https://i.imgur.com/BGePezr.png",
        width:1685,
        height:1125
    },
    {
        src:"https://i.imgur.com/xV9I5eC.png",
        width:2012,
        height:1004
    },
    {
        src:"https://i.imgur.com/E8Yi9Ip.png",
        width:1768,
        height:1179
    },
    {
        src:"https://i.imgur.com/Y2KyM65.png",
        width:1064,
        height:1179
    },
    {
        src:"https://i.imgur.com/Ey6Stwz.png",
        width:1297,
        height:945
    }
];

const BasicRows = () => <Gallery photos={photos} />;
render(<BasicRows />, document.getElementById("root"));
